### ISSUE TITLE
Queue policy over max allowed size on 14+ subscriptions after 7.1.0

### ISSUE THREAD

**Issue by namado** [justeattakeaway/JustSaying#1218]
**Describe the bug**
After the `7.1.0` release the behavior of `SQS Policies` has changed.

Before it created a policy using a wildcard

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "cf4b42494e564ee798ed87916031a5b4",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "sqs:SendMessage",
      "Resource": "arn:aws:sqs:eu-west-1:myAccount:myQueue",
      "Condition": {
        "ArnLike": {
          "aws:SourceArn": "arn:aws:sns:eu-west-1:myAccount:*"
        }
      }
    }
  ]
}
```

Now it creates one per notification

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "5545ed13e631451482115da22da13730",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "sqs:SendMessage",
      "Resource": "arn:aws:sqs:eu-west-1:myAccount:myQueue",
      "Condition": {
        "ArnLike": {
          "aws:SourceArn": "arn:aws:sns:eu-west-1:myAccount:mySubscription1"
        }
      }
    },
    {
      "Sid": "ca25c797959b488cb83a15e4d8aab2a1",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": "sqs:SendMessage",
      "Resource": "arn:aws:sqs:eu-west-1:myAccount:myQueue",
      "Condition": {
        "ArnLike": {
          "aws:SourceArn": "arn:aws:sns:eu-west-1:myAccount:mySubscription2"
        }
      }
    }
  ]
}
```

The issue here is when we have more than 15 subscriptions the policy reaches it limit throwing `Amazon.SQS.AmazonSQSException: Submitted policy is over max allowed size`

**Steps To reproduce**
Adding more than 14 subscriptions will trigger this issue

```csharp
  builder.Subscriptions(options =>
  {
      options.ForTopic<PlanTransactionsAvailable>();
      options.ForTopic<LiabilityDeletedMessage>();
      options.ForTopic<ProviderPlanDetailsReceived>();
      options.ForTopic<AssetDeleted>();
      options.ForTopic<IncomeDeleted>();
      options.ForTopic<ForwardIncomeToAdviserChanged>();
      options.ForTopic<ClientAddressChanged>();
      options.ForTopic<ClientAddressDeleted>();
      options.ForTopic<Recommendation2ProposalChanged>();
      options.ForTopic<ClientChanged>();
      options.ForTopic<ClientDeleted>();
      options.ForTopic<PersonalContactChanged>();
      options.ForTopic<ClientRelationshipCreated>();
      options.ForTopic<ClientRelationshipChanged>();
      options.ForTopic<ClientRelationshipDeleted>();
      options.ForTopic<PersonalContactRelationshipCreated>();
      options.ForTopic<PersonalContactRelationshipChanged>();
      options.ForTopic<PersonalContactRelationshipDeleted>();
      options.ForTopic<PlanDeleted>();
      options.ForTopic<PlanApplicationChanged>();
      options.ForTopic<PlanApplicationStatusChanged>();
      options.ForTopic<IoPlanCreated>();
      options.ForTopic<IoPlanChanged>();
      options.ForTopic<IoPlanStatusUpdated>();
      options.ForTopic<PortfolioOperationMessage>();
  });
```

**Expected behaviour**
Queue and subscription to be created without issues, the same as in version `7.0.1`

**Actual behaviour**
The application crashes throwing the following error

```log
Amazon.SQS.AmazonSQSException: Submitted policy is over max allowed size.
 ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.SQS.Internal.ValidationResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Signer.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceClient.SubscribeQueueToTopicsAsync(IList`1 topicArns, ICoreAmazonSQS sqsClient, String sqsQueueUrl)
   at Amazon.SimpleNotificationService.AmazonSimpleNotificationServiceClient.SubscribeQueueAsync(String topicArn, ICoreAmazonSQS sqsClient, String sqsQueueUrl)
   at JustSaying.AwsTools.QueueCreation.AmazonQueueCreator.SubscribeQueueAndApplyFilterPolicyAsync(IAmazonSimpleNotificationService amazonSimpleNotificationService, String topicArn, IAmazonSQS amazonSQS, Uri queueUrl, String filterPolicy) in /_/src/JustSaying/AwsTools/QueueCreation/AmazonQueueCreator.cs:line 114
   at JustSaying.AwsTools.QueueCreation.AmazonQueueCreator.<>c__DisplayClass4_0.<<EnsureTopicExistsWithQueueSubscribed>g__StartupTask|0>d.MoveNext() in /_/src/JustSaying/AwsTools/QueueCreation/AmazonQueueCreator.cs:line 62
--- End of stack trace from previous location ---
   at JustSaying.JustSayingBus.StartAsync(CancellationToken stoppingToken) in /_/src/JustSaying/JustSayingBus.cs:line 145
```

**System information:**
 - OS: [Windows 10 , CentOS 7]
 - Library Version [7.1.0]
 - .NET version - .Net 6

**Additional context**
I couldn't find anything in the documentation regarding how to specify the policy, and looking at the code I se we can add a `FilterPolicy` but it seems to only apply to the notification itself and the Queue policy is created with all the notifications.

Are we supposed to use this or some other configuration method to fix the issue or is this an unintended change?

**Comment by hwoodiwiss** [comment]
@namado Thanks for reporting this, we'll be publishing a fix to this on Monday per https://github.com/justeattakeaway/JustSaying/pull/1220
